### ISSUE TITLE
Merge camillagui and camillagui-backend into one Git repo

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui-backend#10]
Even though camillagui and camillagui-backend are implemented using different techniques, I think they are both part of the same application. The logical dependency between both is quite strong.
Implementing a feature often requires at least one commit(or PR) for each project.
I think, merging them would simplify development and project setup.

This can be done while keeping the git history of both projects - we have done this at my company.

**Comment by JWahle** [comment]
This would prevent issues like #11.

**Comment by HEnquist** [comment]
I'll take a look. They are closely tied together, but also separate in some sense. What I do when working on them is that I implement some change in the backend first, and use Postman to make sure it's doing what it's supposed to. Then when working on the frontend I change the FLASKURL constant and run it with "npm start". Then the backend should be running in debug mode (by just giving it "debug" as a command line argument). I don't build the frontend and put it in the build dir until I'm done and just want to check that it's all ok.

**Comment by HEnquist** [comment]
Some winter cleaning :) 
I have considered the suggestion, and come to the conclusion that I prefer to keep the gui and backend separate.
