### ISSUE TITLE
Use relative paths for filter coeff files

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui-backend#19]
@JWahle is the realtive path against the active config not working something temporary ?

Before it worked well with relative paths against the config.yml for the plotting.
This will make it less portable for users (they have to know where the the files will be on the specific target).
If it keeps this way I need to patch in moOde all existing or new user uploaded config files to use abs path.

_Originally posted by @bitkeeper in https://github.com/HEnquist/camillagui-backend/issues/18#issuecomment-784221869_

**Comment by JWahle** [comment]
@bitkeeper I thought it never worked - I'll have a look at what breaks it now.

**Comment by JWahle** [comment]
@bitkeeper are you sure, plotting for convolution filters ever worked with relative file paths?
I reverted back to just before my first commit and it doesn't work for me (backend back to `03abebea2dc490961167d06ed2e96f96e73bbda3` and frontend back to `3d56109e0bcaca0302f71ea635dc7e0f9b503048`).

**Comment by bitkeeper** [comment]
@JWahle you are completely right about that, my mistake, I prob mixed it up with the plot of PEQ filters.
And before that is was alway required to 'load from cdsp' and in that way the files names returned by cdsp where are full path names.

**Comment by JWahle** [comment]
I also think, GUI support for relative filter paths would be nice to have, but I'm not sure, if this is worth the hassle.
I'll try an implementation, but no promises here :)

**Comment by bitkeeper** [comment]
@JWahle so I can remove the rel to abs patch of config files in moOde ?

**Comment by JWahle** [comment]
@bitkeeper yes, I think so.
On a side note: Henrik has not tested this, but an implementation to automatically set the parameters for convolution files (https://github.com/HEnquist/camillagui/issues/40) is also in the `develop` branch. I'd appreciate, if you could try it out.
