### ISSUE TITLE
[offline mode] no active config shown

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camillagui-backend#20]
Not active config shown. When using the online version this doesn't occure.

Steps to reproduce:

1. change link to active config a.yml
2. start camillagui backend
3. open web gui 
4. [result: correct config loaded and name on the left panel]
5. close web gui
6. next change link active config to b.yml 
7. open webgui
8. [result: no config loaded and missing name on the left panel]
![image](https://user-images.githubusercontent.com/1525169/109165654-15c7d580-777c-11eb-9948-f450d7b1a4ae.png)

If I do a camillagui-backedn restart before step 7. everything is fine.
As note during step 6 also a SIGHUP is send to the running camilladsp (which in this case is the backup cdsp).

**Comment by JWahle** [comment]
I cannot reproduce the issue on my Ubuntu PC and I don't understand, how this could happen.
As far as I see, you create the link via `ln -s -f TARGET LINK_NAME` - exactly like the camillagui-backend does.
The backend does not store any internal state regarding the active config, other than the link.
I will have a look at this on my Raspi with the new moOde test release.

**Comment by JWahle** [comment]
The problem is, that your SIGHUP signal kills the internal CDSP started by the GUIs backend.
I created this [issue](https://github.com/HEnquist/camilladsp/issues/96) in CDSP to solve the problem.

**Comment by bitkeeper** [comment]
Thanks for finding out, good catch!
