### ISSUE TITLE
Empty Build Directory - Web Interface Fails With "404"

### ISSUE THREAD

**Issue by redger-au** [HEnquist/camillagui-backend#34]
I downloaded & installed R0.7.1 camillagui .. and managed to run it ... BUT could only generate 404 (page not found) error. The build directory in my download contained only 1 file ("_.put_statics_here_")

I shamelessly copied the build directory from MoodeAudio (/opt/camillagui/build) and can now see a nice Camilla page in the browser ... albeit with lots of errors

Perhaps files have been accidentally removed and can be restored ?

Fwiw I see lots of these errors from camillagui itself when using the Moode's build directory with current "master"

> OSError: Invalid response received: {"Invalid":{"error":"unknown variant `GetCaptureSignalRms`, expected one of `SetConfigName`, `SetConfig`, `SetConfigJson`, `Reload`, `GetConfig`, `ReadConfig`, `ReadConfigFile`, `ValidateConfig`, `GetConfigJson`, `GetConfigName`, `GetSignalRange`, `GetCaptureRate`, `GetUpdateInterval`, `SetUpdateInterval`, `GetVersion`, `GetState`, `GetRateAdjust`, `GetClippedSamples`, `GetBufferLevel`, `Exit`, `Stop`, `None` at line 1 column 21"}}
playbacksignalrms
Error handling request
Traceback (most recent call last):
  File "/storage/.kodi/userdata/re_data/camilladsp/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/storage/.kodi/userdata/re_data/camilladsp/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/storage/.kodi/userdata/re_data/camilladsp/camilla_companions/camillagui-backend-master/views.py", line 82, in get_list_param
    result = cdsp.get_playback_signal_rms()
  File "/storage/.kodi/userdata/re_data/camilladsp/site-packages/camilladsp/camilladsp.py", line 167, in get_playback_signal_rms
    sigrms = self._query("GetPlaybackSignalRms")
  File "/storage/.kodi/userdata/re_data/camilladsp/site-packages/camilladsp/camilladsp.py", line 62, in _query
    return self._handle_reply(command, rawrepl)
  File "/storage/.kodi/userdata/re_data/camilladsp/site-packages/camilladsp/camilladsp.py", line 82, in _handle_reply
    raise IOError("Invalid response received: {}".format(rawreply))
OSError: Invalid response received: {"Invalid":{"error":"unknown variant `GetPlaybackSignalRms`, expected one of `SetConfigName`, `SetConfig`, `SetConfigJson`, `Reload`, `GetConfig`, `ReadConfig`, `ReadConfigFile`, `ValidateConfig`, `GetConfigJson`, `GetConfigName`, `GetSignalRange`, `GetCaptureRate`, `GetUpdateInterval`, `SetUpdateInterval`, `GetVersion`, `GetState`, `GetRateAdjust`, `GetClippedSamples`, `GetBufferLevel`, `Exit`, `Stop`, `None` at line 1 column 22"}}
capturerate
44100
rateadjust
0.0
bufferlevel
0
clippedsamples
0

Thanks for a great DSP facility, fantastic work !

PS THis is camilladsp running on Coreelec (AMLogic S905x3 box) which is great ... it's working in that it reads data from Loopback and writes to the hardware sound device so the basic functionality is working ... juyst struggling with the gui

**Comment by HEnquist** [comment]
Hi! It looks as if you downloaded just the source code of the backend. Get the zip instead: https://github.com/HEnquist/camillagui-backend/releases/download/v0.7.1/camillagui.zip 
This includes the frontend that goes in the build dir.
The error about `GetPlaybackSignalRms` is probably a version mismatch. Which camilladsp version did you use? Try with the latest release, then that error should go away. Also check that you have the latest pycamilladsp and pycamilladsp-plot installed.

**Comment by redger-au** [comment]
You're right !
Sorry, false alarm - my mistake :(

thanks for clarifying :)
