### ISSUE TITLE
[1.0.0rc1] Missing default value for config entry 'log_file'

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camillagui-backend#40]
Did a test run with 1.0.0rc1.
At startup of the gui backend, the backend crashed due missing value in config:

```
May 03 11:19:31 raspberrypi python3[1536009]: Traceback (most recent call last):
May 03 11:19:31 raspberrypi python3[1536009]:   File "/opt/camillagui/main.py", line 13, in <module>
May 03 11:19:31 raspberrypi python3[1536009]:     app["log_file"] = config["log_file"]
May 03 11:19:31 raspberrypi python3[1536009]: KeyError: 'log_file
```

Maybe set the default value at `backend/settings.py` in function `get_config`  to `None`:
```diff
+    if "log_file" not in config:
+        config["log_file"] = None
```

This will be backward compatible with already existing config files and an at least provides backend that starts.

**Comment by HEnquist** [comment]
Thanks! I'll fix asap.

**Comment by HEnquist** [comment]
Can you please try 1.0.0-rc2?

**Comment by bitkeeper** [comment]
rc2 works like a charm!
Thanks
