### ISSUE TITLE
Additional properties are not allowed errors. version conflicts?

### ISSUE THREAD

**Issue by alex-vyverman** [HEnquist/camillagui-backend#43]
Hi,

I'm running 
CamillaDSP 1.0.3
pyCamillaDSP 1.0.0
Backend 1.0.1
On MacOS

The backend works fine on it's own. But the gui throws errors like:

- Additional properties are not allowed ('enable_resampling', 'resampler_type' were unexpected)
- Additional properties are not allowed ('change_format' was unexpected)

My guess is that these are settings that are incompatible, or that the gui assumes are incompatible.
But I cannot figure out which combination of versions I need to get it running properly without these errors.

Could someone point me in the right direction?
Many thanks!

**Comment by HEnquist** [comment]
Those errors mean that the backend is using the rules for v2.0 to validate the config. Those come from pycamilladsp-plot, so I guess you have somehow ended up running a newer version of that. You need v1.0.2.
https://github.com/HEnquist/pycamilladsp-plot/releases/tag/v1.0.2

**Comment by alex-vyverman** [comment]
An oversight on my part. I dabbled with V2 alpha, downgraded pycamilladsp when going back to v1.x, but forgot pycamilladsp-plot.

That's the cue where I should be using venv's/conda env's 🤓

Thanks for you kind response!

**Comment by HEnquist** [comment]
Yeah isolated environments are pretty nice 😁
