### ISSUE TITLE
[next30] import legacy config with stdin

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camillagui-backend#68]
Noticed that import of the legacy goes almost well, espically the patching of channel to channels saves time.
(The change from channel to channels propably also requires and update from REW).

An issue I noticed is that legacy configs that use for capture config with type:file/filename:stdin is not correctly migrated.

Situation:
* legacy file with capture type set to file
* and filename to Stdin

Expect was:
* the filename property removed
* type set to Stdin

**Comment by HEnquist** [comment]
You mean when filename is set to "/dev/stdin"? That is still allowed, there should be no need to migrate. 

REW import should work, unless some very recent REW version has introduced changes that cause trouble.

**Comment by HEnquist** [comment]
Closing as there doesn't seem to be any problem. Please reopen if I have misunderstood anything.
