### ISSUE TITLE
Integration of CamillaGUI into WebUI

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui-backend#8]
Hi Henrik,

@bitkeeper and I are currently working on CamillaDSP integration into [moOde](http://moodeaudio.org) audio player for Raspi. We are trying to make it as user friendly as possible and thus would like to provide some values to and hide some options from the CamillaGUI "Devices" Tab.

CamillaDSP is called through scripple's ALSA CDSP plugin, so some parameters are always overridden. I think it would be useful, if all parameters that can be overridden this way could be configured to be hidden individually. Under the hood, they would be replaced with default values, so config checks still work. AFAIK currently, this would apply to `channels`, `samplerate`, `input` `sampleformat` and `extra_samples`

To my knowledge, `target_level`, `enable_rate_adjust` and `adjust_period` are irrelevant to File/Stdin inputs and can probably be automatically hidden, when one of these inputs is selected. Otherwise a dedicated setting to disable each of these would be nice.
Maybe this also somewhat applies to `queuelimit` - I don't know, if there is any valid reason to set it to something other than 1 for File/Stdin inputs. If there is, it should probably be visible with a default of 1.

An option to hide input and/or output devices and use some defaults would also be nice. In our case, the input device is always `stdin` and the output device is already configured through the moOde UI.

From a configuration point of view I think of these additional options in camillagui.yml:
- option to set the location of a default camilladsp config
    - all default values are provided through this config
    - this config would be loaded into the UI when camillagui is opened in the browser
    - not sure, if an additional button for this is needed, since this is no different than reloading the page (F5)
    - the config should not be cached, so it could be updated by moOde, while CamillaGUI is open
- options to hide
    - samplerate
    - sampleformat
    - channels
    - extrasamples
    - capture device
    - playback device

**Comment by HEnquist** [comment]
Hi,
Let's make sure I understand how this is supposed to work first. Since the CamillaDSP process will be restarting once in a while when the plugin closes it, the config must be written to file all the time. Does that mean the "apply" button should then both save to file, and send to the currently running process?

> option to set the location of a default camilladsp config 
> - all default values are provided through this config
> - this config would be loaded into the UI when camillagui is opened in the browser
> - not sure, if an additional button for this is needed, since this is no different than reloading the page (F5)

These should be no problem.

> - the config should not be cached, so it could be updated by moOde, while CamillaGUI is open

You mean that moOde would update the default config file, and the gui should pick this up? It's doable, then the backend needs to watch the file to catch when it changes, and some way to communicate this to the gui itself.

> options to hide
> - samplerate
> - ...

This could perhaps be done by hiding anything that is included in the default config.

Do you intend to support using CamillaDSP to make crossovers? If not, everything related to Mixers could also be hidden. That would require that moOde can select a multichannel output device, and set the right number of channels.

From a quick glance all these things are doable, but I'll have to look more closely.

**Comment by JWahle** [comment]
Alright, maybe we should talk about the general workflow first - I mainly thought about what the user sees, when CamillaGUI is opened. I see 2 use-cases for this:
1. There are no configs and we would like to provide as much as possible to a starter config.
2. An existing config shall be edited (or at least be used as starting point for a new config).

> Since the CamillaDSP process will be restarting once in a while when the plugin closes it, the config must be written to file all the time. Does that mean the "apply" button should then both save to file, and send to the currently running process?

Probably yes. There may be cases where different buttons for apply and save would be handy, but this seems much simpler to me. "apply" should probably be renamed to "save & apply".

For moOde we want to provide some kind of config management, where the user can upload/download/delete/edit config files and select the config for CamillaDSP. 

bitkeeper already implemented most of this - the only piece missing is the "Edit" button.
This is how it currently looks:
![moode-camilladsp-integration](https://user-images.githubusercontent.com/7657699/103601633-5472a980-4f0a-11eb-913b-79ed5968f587.jpeg)

So, for our use-case it would be sufficient, if CamillaGUI could be instructed to work with just one config file. This means that this config is loaded when the user opens the GUI and it would also be written, when the user saves. A suitable name for this property might be `current_config` (instead of `default_config`).
Of course, it would be nicer, if CamillaGUI would provide fully fledged configuration management, but that would be much more work on your side and we don't really need it.

> You mean that moOde would update the default config file, and the gui should pick this up? It's doable, then the backend needs to watch the file to catch when it changes, and some way to communicate this to the gui itself.

Actually, I'm not sure, why I formulated it that way. I don't think there is a need to watch the file - just provide the current version, when the user opens/reloads the GUI.

> This could perhaps be done by hiding anything that is included in the default config.

I also thought of this, but not all properties with default values shall be hidden (e.g. chunk_size and maybe other properties, depending on use-case). So, I suggest, you reuse the config loading mechanism, that is already implemented and allow to configure which properties are hidden.

> Do you intend to support using CamillaDSP to make crossovers?

I will say yes, as I have already done just that and am very pleased with the result.

**Comment by bitkeeper** [comment]
Since yesterday also the edit button is available. Camillagui is running as a systemd service and can be started/stopped with a toggle button.

![image](https://user-images.githubusercontent.com/1525169/103690860-a01e6500-4f95-11eb-9a48-5d1296fe7882.png)

I can imagine that hiding the controls is an edge case for normal use. Another option with less impact would be adding id to the React Components, so we could hide just by adding a css.

**Comment by JWahle** [comment]
@HEnquist have you made up your mind about this?
If you agree to these changes, I could implement at least some of them.

**Comment by HEnquist** [comment]
Sorry I'm having too many projects running at the same time, the gui stuff tends to end up last in the queue.

I have thought a little about this now. For default config, it would make a lot of sense to provide a default config from the backend, configured by a setting there. Right now the default config is hardcoded in the frontend itself, not very elegant.

For hiding settings, this could be done by providing a yaml file with a similiar layout to the config, but where every value is a boolean for if the setting should be displayed or not, defaulting to being displayed if it's not included in the file. I would then start by letting the backend handle substituting the hidden values in the config, and letting the frontend handle what fields should be hidden (using the show/hide config provided by the backend).

I will be busy working on FFTs and the resampler for a while longer. If you can start on this yourselfves that would be great.

**Comment by JWahle** [comment]
> Sorry I'm having too many projects running at the same time, the gui stuff tends to end up last in the queue.

That's what I thought ;)
I'll see, what I can do.

**Comment by JWahle** [comment]
FYI, I just implemented the load from/save to default config.
I will probably create a PR tomorrow.

**Comment by JWahle** [comment]
With PRs https://github.com/HEnquist/camillagui/pull/14 #14 and #15 merged, this is finished ;)
